### ISSUE TITLE
Erreur de lecture d'entier

### ISSUE THREAD

**Issue by athimel** [athimel/mh-dla-notifier#2]
> java.lang.RuntimeException: Unable to start receiver org.zoumbox.mh_dla_notifier.Receiver: java.lang.NumberFormatException: Invalid int: "margin:0"
>   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2680)
>   at android.app.ActivityThread.access$1700(ActivityThread.java:156)
>   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
>   at android.os.Handler.dispatchMessage(Handler.java:102)
>   at android.os.Looper.loop(Looper.java:211)
>   at android.app.ActivityThread.main(ActivityThread.java:5373)
>   at java.lang.reflect.Method.invoke(Native Method)
>   at java.lang.reflect.Method.invoke(Method.java:372)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
> Caused by: java.lang.NumberFormatException: Invalid int: "margin:0"
>   at java.lang.Integer.invalidInt(Integer.java:138)
>   at java.lang.Integer.parse(Integer.java:410)
>   at java.lang.Integer.parseInt(Integer.java:367)
>   at java.lang.Integer.parseInt(Integer.java:334)
>   at org.zoumbox.mh_dla_notifier.sp.PublicScripts.pushToTroll(PublicScripts.java:129)
>   at org.zoumbox.mh_dla_notifier.sp.PublicScripts.pushToTroll(PublicScripts.java:161)
>   at org.zoumbox.mh_dla_notifier.profile.v2.ProfileProxyV2.fetchScripts(ProfileProxyV2.java:313)
>   at org.zoumbox.mh_dla_notifier.profile.v2.ProfileProxyV2.refreshDLA(ProfileProxyV2.java:391)
>   at org.zoumbox.mh_dla_notifier.Receiver.refreshDla(Receiver.java:309)
>   at org.zoumbox.mh_dla_notifier.Receiver.onReceive(Receiver.java:223)
>   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2673)
>   ... 9 more

**Comment by athimel** [comment]
Y'a rien à faire, c'est probablement lié à un pb de connectivité
